### ISSUE TITLE
Orientation problem

### ISSUE THREAD

**Issue by sashakozack** [torokati44/ruffle-android#32]
When the screen orientation changes, the image is stretched

**Comment by torokati44** [comment]
This got fixed by switching to `GameActivity`.
While the content is no longer stretched, the majority of the screen is taken up by the keyboard:
![image](https://user-images.githubusercontent.com/288816/226835900-3da11340-0a1d-467a-b913-bbce3c50264c.png)

It should be hidden in landscape mode, I guess...
